version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      
      - run:
          name: Download osstool
          command: |
            curl -o oss http://gosspublic.alicdn.com/ossutil/1.6.6/ossutil64
            chmod 755 oss

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: 
          name: Unit tests
          command: mvn test
          
      - run: 
          name: packaging jar with dependencies
          command: mvn clean compile assembly:single
            
      - run:
          name: Distribute jar file
          command: |
            ./oss cp target/javascool-light.jar oss://javascool/${CIRCLE_BRANCH}/javascool-light.jar -e oss-us-east-1.aliyuncs.com -i ${oss_access_key_id} -k ${oss_access_key_secret} -f
            echo "Artifact available at : https://javascool.oss-us-east-1.aliyuncs.com/${CIRCLE_BRANCH}/javascool-light.jar"
